name: base

channels:
  - conda-forge
  - pytorch
  - nordicesmhub
  - bioconda
  - defaults

dependencies:
  - python=3.6
  - numpy >=1.11.0
  - iris >=2.1.0
  - xarray >=0.10.8
  - pandas >=0.22.0
  - cartopy >=0.16.0
  - numpy >=1.14
  - matplotlib =2.2.*
  - seaborn >=0.8.1
  - geopy >=1.17.0
  - basemap
  - netcdf4
  - cis
  - bokeh
  - pyaerocom
  - metpy
  - python-cdo
  - cdo
  - sympy
  - jupyter
  - ipykernel
  - notebook >=5.6.0
  - ipypublish
  - bibtexparser
  - latexmk
  - llvmlite
  - cython
  - numba
  - scipy
  - scikit-learn
  - jupyterlab
  - nc-time-axis
  - PyTables
  - xlrd
  - ambhas
  - memory_profiler
  - plotly
  - cufflinks
  - pytorch
  - torchvision
  - ipyleaflet=0.9.2
  - rasterio
  - tqdm
  - requests
  - pillow
  - branca
  - geopandas
  - voila
  - nodejs
  - pythreejs
  - bqplot
  - cv2
  - pip:
      - dask_labextension
      - ipydatawidgets
      - sidecar

